# Generated by Django 5.1.3 on 2025-02-14 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OliveOilCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος λιπασμάτων')),
                ('irrigation_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος ποτίσματος')),
                ('elga_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ΕΛΓΑ')),
                ('osde_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος ΟΣΔΕ')),
                ('agronomist_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Κόστος Γεωπόνου')),
                ('certification_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Πιστοποιήσεις')),
                ('daily_wage', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ημερομίσθιο')),
                ('working_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ημέρες εργασίας')),
                ('machinery_maintenance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Συντήρηση μηχανημάτων')),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Καύσιμα')),
                ('equipment_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Παρελκόμενα')),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Μεταφορικά')),
                ('total_oil_production', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Συνολική παραγωγή (kg)')),
                ('mill_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ποσοστό ελαιοτριβείου (%)')),
                ('date_calculated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
