# Generated by Django 5.1.3 on 2025-02-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oliveoilcalculation',
            name='other_works_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Λοιπές εργασίες'),
        ),
    ]
