# Generated by Django 5.1.3 on 2025-02-15 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_calculator', '0002_oliveoilcalculation_other_works_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oliveoilcalculation',
            name='fertilizer_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Λίπανση και φυτοπροστασία'),
        ),
        migrations.AlterField(
            model_name='oliveoilcalculation',
            name='irrigation_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Άρδευση'),
        ),
        migrations.AlterField(
            model_name='oliveoilcalculation',
            name='other_works_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Λοιπές εργασίες'),
        ),
    ]
